-- Drop sequences	
DROP SEQUENCE SQ_SIF_BATERIA;
DROP SEQUENCE SQ_SIF_BATERIA_CARREG;
DROP SEQUENCE SQ_SIF_CIDADE;
DROP SEQUENCE SQ_SIF_CONCESSIONARIA;
DROP SEQUENCE SQ_SIF_EMPRESA;
DROP SEQUENCE SQ_SIF_ESTACAO;
DROP SEQUENCE SQ_SIF_LINHA;
DROP SEQUENCE SQ_SIF_LOCALIZA_ESTACAO;
DROP SEQUENCE SQ_SIF_LOCOMOTIVA;
DROP SEQUENCE SQ_SIF_REGISTRO;
DROP SEQUENCE SQ_SIF_TRECHO;
DROP SEQUENCE SQ_SIF_VAGAO;
DROP SEQUENCE SQ_SIF_VAGAO_EMPRESA;

-- Drop table		
DROP TABLE T_SIF_BATERIA CASCADE CONSTRAINTS;
DROP TABLE T_SIF_BATERIA_CARREG	CASCADE CONSTRAINTS;
DROP TABLE T_SIF_BATERIA_ESTACAO CASCADE CONSTRAINTS;
DROP TABLE T_SIF_CIDADE	CASCADE CONSTRAINTS;
DROP TABLE T_SIF_CONCESSIONARIA	CASCADE CONSTRAINTS;
DROP TABLE T_SIF_EMPRESA CASCADE CONSTRAINTS;
DROP TABLE T_SIF_ESTACAO CASCADE CONSTRAINTS;
DROP TABLE T_SIF_ESTADO	CASCADE CONSTRAINTS;
DROP TABLE T_SIF_LINHA CASCADE CONSTRAINTS;
DROP TABLE T_SIF_LOCALIZA_ESTACAO CASCADE CONSTRAINTS;
DROP TABLE T_SIF_LOCOMOTIVA CASCADE CONSTRAINTS;
DROP TABLE T_SIF_LOC_BATERIA CASCADE CONSTRAINTS;
DROP TABLE T_SIF_LOC_VAGAO CASCADE CONSTRAINTS;
DROP TABLE T_SIF_REGISTRO CASCADE CONSTRAINTS;
DROP TABLE T_SIF_TRECHO	CASCADE CONSTRAINTS;
DROP TABLE T_SIF_VAGAO CASCADE CONSTRAINTS;
DROP TABLE T_SIF_VAGAO_EMPRESA CASCADE CONSTRAINTS;